### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nthiery** [scottsievert/rst-to-ipynb#2]
Hi @stsievert,
We forgot to discuss the license for the rst-to-ipynb code. Would you be ok going for the revised BSD license, for consistency with Jupyter?

Thanks in advance,

**Comment by stsievert** [comment]
I am okay with this.

I added the license at https://opensource.org/licenses/BSD-3-Clause but haven't pushed yet, is this what you're looking for?

**Comment by nthiery** [comment]
On Tue, Sep 27, 2016 at 04:01:07PM -0700, Scott Sievert wrote:

>    I am okay with this.
> 
>    I added the license at [1]https://opensource.org/licenses/BSD-3-Clause
>    but haven't pushed yet, is this what you're looking for?

Yes indeed. Thanks Scott!

Cheers,
                                        Nicolas

**Comment by stsievert** [comment]
License added!
